apiVersion: v1
kind: Pod
metadata:
  name: resize-demo-no-limit
spec:
  containers:
  - name: demo-g
    image: nginx:latest
    resources:
      requests:
        cpu: "1.0"
        memory: 1G
      limits:
        memory: 1G